import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import useWorldAtlas from "../hooks/useWorldAtlas";
import Map from "../components/Map";
import { ColorScale } from "../types";
import useFile from "../hooks/useFile";

const colorScale: ColorScale = {
  "Non-Voting": "grey",
  A: "yellow",
  N: "red",
  Y: "green",
};

const Home: NextPage = () => {
  const worldAtlas = useWorldAtlas();
  const data = useFile();

  if (!worldAtlas || !data) return <div>Loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>Hello, World!</div>
        {data.vote ? (
          <svg width={1200} height={600}>
            <Map
              worldAtlas={worldAtlas}
              countryVotes={data.vote}
              colorScale={colorScale}
            />
          </svg>
        ) : (
          <div>no votes</div>
        )}
      </main>
    </div>
  );
};

export default Home;
